language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - setup=basic
    - APP_ENV=staging
    - APP_DEBUG=true
    - APP_KEY=ftDMx8ISZHiwGr2bUpYWsu2T4pR1NL5B
    - DB_CONNECTION=mysql
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync
    - DB_HOST=127.0.0.1
    - DB_USERNAME=travis
    - DB_DATABASE=mazedlx_net

sudo: false

services:
  - mysql

before_install:
  - travis_retry composer self-update
  - mysql -e "create database IF NOT EXISTS mazedlx_net;" -uroot

before_script:
    - php artisan migrate:refresh --seed

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit
